gantt
    dateFormat  YYYY-MM-DD
    title      Group Four: Predicting Conflict Escalation

    section Precapstone proposal
    Chapter 01                  :done, pre1, 2023-01-10, 2023-01-12
    Chapter 02                  :done, pre2, 2023-01-17, 3d
    Chapter 03                  :done, pre3, 2023-01-19, 2d

    section Compute and Data
    Cloud infra                 :active, cloud, after pre3, 1w
    Data ingestion pipelines    :done, datapipe, after pre3, 2w
    GDELT full dataset          :active, gdelt, after cloud, 2w
    GDELT sample dataset        :done, gsample, after pre3, 1w
    ACLED dataset               :done, acled, after pre3, 1w
    Sample training dataset     :active, sample, after acled, 1w
    Full training dataset       :dataset, after gdelt, 1w

    section Modelling
    Establish models and approaches to evaluate :done,  m1, after pre3, 1w
    Establish performance evaluation metrics    :active, m2, after a1, 1w
    Model prototyping                           :proto, after dataset, 3w
    Model evaluation                            :eval, after proto, 5w
    Working final model                         :model, after eval, 2w
 
    section Stretch goals
    API or UI                                   :api, after proto, 2w
    Deployed model                              :prod, after model, 1w

    section Capstone paper
    Draft report                                :draft, after eval, 2w
    Final report                                :report, after draft, 1w
    Presentation                                :pres, after report, 1w